version: '3.9'

services:
  db:
    container_name: postgresCon
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres123'
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - 5434:5432

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'postgres@postgres.com'
      PGADMIN_DEFAULT_PASSWORD: 'postgres123'
    ports:
      - 8080:80
    volumes:
      - ./pgadmin-data:/var/lib/pgadmin
    depends_on:
      - db
volumes:
  postgres-db-volume:
  pgadmin-data:      
